# Generated by Django 5.1.15 on 2026-03-12 20:44

import common.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta Başlık')),
                ('meta_title_tr', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık')),
                ('meta_title_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta Açıklama')),
                ('meta_description_tr', models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama')),
                ('meta_description_en', models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Hero Başlık')),
                ('hero_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hero Başlık')),
                ('hero_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hero Başlık')),
                ('hero_image', models.ImageField(blank=True, upload_to='careers/hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Hero Görsel')),
                ('intro_label', models.CharField(blank=True, max_length=100, verbose_name='Tanıtım Etiket')),
                ('intro_label_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tanıtım Etiket')),
                ('intro_label_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tanıtım Etiket')),
                ('intro_title', models.CharField(blank=True, max_length=200, verbose_name='Tanıtım Başlık')),
                ('intro_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tanıtım Başlık')),
                ('intro_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tanıtım Başlık')),
                ('intro_description', models.TextField(blank=True, verbose_name='Tanıtım Açıklama')),
                ('intro_description_tr', models.TextField(blank=True, null=True, verbose_name='Tanıtım Açıklama')),
                ('intro_description_en', models.TextField(blank=True, null=True, verbose_name='Tanıtım Açıklama')),
                ('intro_image', models.ImageField(blank=True, upload_to='careers/intro/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Tanıtım Görsel')),
                ('intro_button_text', models.CharField(blank=True, max_length=100, verbose_name='Buton Metni')),
                ('intro_button_text_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Buton Metni')),
                ('intro_button_text_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Buton Metni')),
                ('intro_button_url', models.CharField(blank=True, max_length=300, verbose_name='Buton URL')),
                ('positions_title', models.CharField(blank=True, max_length=200, verbose_name='Pozisyonlar Başlık')),
                ('positions_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pozisyonlar Başlık')),
                ('positions_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pozisyonlar Başlık')),
                ('why_title', models.CharField(blank=True, max_length=200, verbose_name='Neden Biz Başlık')),
                ('why_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Neden Biz Başlık')),
                ('why_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Neden Biz Başlık')),
                ('why_description', models.TextField(blank=True, verbose_name='Neden Biz Açıklama')),
                ('why_description_tr', models.TextField(blank=True, null=True, verbose_name='Neden Biz Açıklama')),
                ('why_description_en', models.TextField(blank=True, null=True, verbose_name='Neden Biz Açıklama')),
            ],
            options={
                'verbose_name': 'Kariyer Sayfa Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100, verbose_name='Departman Adı')),
                ('name_tr', models.CharField(max_length=100, null=True, verbose_name='Departman Adı')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Departman Adı')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='İkon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=300, verbose_name='Pozisyon Başlığı')),
                ('title_tr', models.CharField(max_length=300, null=True, verbose_name='Pozisyon Başlığı')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='Pozisyon Başlığı')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Slug')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lokasyon')),
                ('location_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lokasyon')),
                ('location_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lokasyon')),
                ('work_type', models.CharField(choices=[('remote', 'Uzaktan'), ('onsite', 'Ofiste'), ('hybrid', 'Hibrit')], default='onsite', max_length=20, verbose_name='Çalışma Şekli')),
                ('employment_type', models.CharField(choices=[('full_time', 'Tam Zamanlı'), ('part_time', 'Yarı Zamanlı'), ('intern', 'Stajyer'), ('contract', 'Sözleşmeli')], default='full_time', max_length=20, verbose_name='Çalışma Tipi')),
                ('experience_level', models.CharField(blank=True, max_length=100, verbose_name='Deneyim Seviyesi')),
                ('experience_level_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Deneyim Seviyesi')),
                ('experience_level_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Deneyim Seviyesi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Sorumluluklar')),
                ('responsibilities_tr', models.TextField(blank=True, null=True, verbose_name='Sorumluluklar')),
                ('responsibilities_en', models.TextField(blank=True, null=True, verbose_name='Sorumluluklar')),
                ('requirements', models.TextField(blank=True, verbose_name='Beklentiler')),
                ('requirements_tr', models.TextField(blank=True, null=True, verbose_name='Beklentiler')),
                ('requirements_en', models.TextField(blank=True, null=True, verbose_name='Beklentiler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='careers.department', verbose_name='Departman')),
            ],
            options={
                'verbose_name': 'İş İlanı',
                'verbose_name_plural': 'İş İlanları',
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(common.models.AutoSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('cv_file', models.FileField(upload_to='careers/cv/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='CV Dosyası')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Ön Yazı')),
                ('kvkk_accepted', models.BooleanField(default=False, verbose_name='KVKK Onayı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='careers.jobposition', verbose_name='Pozisyon')),
            ],
            options={
                'verbose_name': 'İş Başvurusu',
                'verbose_name_plural': 'İş Başvuruları',
                'ordering': ['-created_at'],
            },
        ),
    ]
