# Generated by Django 5.1.15 on 2026-03-13 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='careers/hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görsel'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='intro_image',
            field=models.ImageField(blank=True, upload_to='careers/intro/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Tanıtım Görsel'),
        ),
    ]
