# Generated by Django 5.1.15 on 2026-03-13 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_careersettings_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.FileField(blank=True, upload_to='careers/departments/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])], verbose_name='İkon'),
        ),
    ]
