# Generated by Django 5.1.15 on 2026-03-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_department_icon_to_filefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='full_name',
        ),
        migrations.AddField(
            model_name='careersettings',
            name='apply_button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Genel Başvuru Buton Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='apply_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Genel Başvuru Buton Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='apply_button_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Genel Başvuru Buton Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='apply_button_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='Genel Başvuru Buton URL'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='İletişim Buton Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İletişim Buton Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_button_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İletişim Buton Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_button_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='İletişim Buton URL'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_description',
            field=models.TextField(blank=True, verbose_name='İletişim Açıklama'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='İletişim Açıklama'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='İletişim Açıklama'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='İletişim Etiket'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İletişim Etiket'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İletişim Etiket'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='İletişim Başlık'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İletişim Başlık'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='contact_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İletişim Başlık'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='positions_button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pozisyonlar Buton Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='positions_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pozisyonlar Buton Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='positions_button_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pozisyonlar Buton Metni'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Soyad'),
        ),
    ]
