# Generated by Django 5.1.15 on 2026-03-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_careers_cta_split_name_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Soyad'),
        ),
    ]
