# Generated by Django 5.1.15 on 2026-03-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_alter_jobapplication_first_name_and_more 2'),
        ('careers', '0005_alter_jobapplication_first_name_and_more'),
    ]

    operations = [
    ]
