# Generated by Django 5.1.15 on 2026-04-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_merge_20260319_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersettings',
            name='kvkk_text',
            field=models.TextField(blank=True, verbose_name='KVKK Onay Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='kvkk_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='KVKK Onay Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='kvkk_text_tr',
            field=models.TextField(blank=True, null=True, verbose_name='KVKK Onay Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='why_button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Neden Biz Buton Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='why_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Neden Biz Buton Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='why_button_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Neden Biz Buton Metni'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='why_button_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='Neden Biz Buton URL'),
        ),
    ]
