# Generated by Django 5.1.15 on 2026-04-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_careersettings_add_why_button_kvkk'),
    ]

    operations = [
        migrations.AddField(
            model_name='careersettings',
            name='apply_form_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Başvuru Form Başlığı'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='apply_form_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başvuru Form Başlığı'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='apply_form_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başvuru Form Başlığı'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='newsletter_placeholder',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bülten Placeholder'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='newsletter_placeholder_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bülten Placeholder'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='newsletter_placeholder_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bülten Placeholder'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='newsletter_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bülten Başlığı'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='newsletter_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Başlığı'),
        ),
        migrations.AddField(
            model_name='careersettings',
            name='newsletter_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Başlığı'),
        ),
    ]
