# Generated by Django 5.1.15 on 2026-04-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_careersettings_copy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersettings',
            name='app_feedback_error_message_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Başvuru Hata Mesajı'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_feedback_error_message_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Başvuru Hata Mesajı'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_feedback_missing_cv_message_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='CV Eksik Mesajı'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_feedback_missing_cv_message_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='CV Eksik Mesajı'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_feedback_success_message_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Başvuru Başarı Mesajı'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_feedback_success_message_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Başvuru Başarı Mesajı'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_field_cover_letter_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ön Yazı Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_field_cover_letter_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ön Yazı Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_field_cv_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CV Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_field_cv_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CV Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_field_email_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-posta Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_field_email_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-posta Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_field_first_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_field_first_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_field_last_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_field_last_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_field_phone_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_field_phone_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_form_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başvuru Form Alt Başlığı'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_form_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Başvuru Form Alt Başlığı'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_placeholder_cover_letter_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ön Yazı Placeholder'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_placeholder_cover_letter_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ön Yazı Placeholder'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_placeholder_cv_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CV Placeholder'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_placeholder_cv_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CV Placeholder'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_placeholder_email_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-posta Placeholder'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_placeholder_email_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-posta Placeholder'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_placeholder_first_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Placeholder'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_placeholder_first_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Placeholder'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_placeholder_last_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad Placeholder'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_placeholder_last_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad Placeholder'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_placeholder_phone_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon Placeholder'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_placeholder_phone_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon Placeholder'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_position_summary_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pozisyon Özet Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_position_summary_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pozisyon Özet Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_privacy_consent_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Rıza Metni'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_privacy_consent_text_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Rıza Metni'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_privacy_link_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gizlilik Linki Metni'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_privacy_link_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gizlilik Linki Metni'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_submit_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başvuru Gönder Butonu'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_submit_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başvuru Gönder Butonu'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_submitting_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başvuru Gönderiliyor'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_submitting_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Başvuru Gönderiliyor'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_upload_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CV Yükle Butonu'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='app_upload_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CV Yükle Butonu'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_expectations_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beklentiler Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_expectations_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beklentiler Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_meta_department_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departman Meta Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_meta_department_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departman Meta Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_meta_employment_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Çalışma Tipi Meta Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_meta_employment_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Çalışma Tipi Meta Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_meta_experience_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deneyim Meta Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_meta_experience_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Deneyim Meta Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_meta_location_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lokasyon Meta Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_meta_location_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lokasyon Meta Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_meta_work_type_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Çalışma Şekli Meta Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_meta_work_type_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Çalışma Şekli Meta Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_responsibilities_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sorumluluklar Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='job_responsibilities_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sorumluluklar Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='newsletter_error_message_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bülten Hata Mesajı'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='newsletter_error_message_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bülten Hata Mesajı'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='newsletter_submit_aria_label_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Gönder Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='newsletter_submit_aria_label_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Gönder Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='newsletter_success_message_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bülten Başarı Mesajı'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='newsletter_success_message_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bülten Başarı Mesajı'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='positions_count_label_suffix_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pozisyon Sayı Suffix'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='positions_count_label_suffix_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pozisyon Sayı Suffix'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='positions_next_aria_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sonraki Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='positions_next_aria_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sonraki Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='positions_previous_aria_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Önceki Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='positions_previous_aria_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Önceki Aria Etiketi'),
        ),
    ]
