# Generated by Django 5.1.15 on 2026-04-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_alter_careersettings_app_feedback_error_message_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='Değerlendirme Notu'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='review_status',
            field=models.CharField(choices=[('new', 'Yeni'), ('reviewing', 'İnceleniyor'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi')], default='new', max_length=20, verbose_name='Değerlendirme Durumu'),
        ),
    ]
