# Generated by Django 5.1.15 on 2026-05-22 08:26

import common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0011_add_review_status_to_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersettings',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('careers/hero/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görsel'),
        ),
        migrations.AlterField(
            model_name='careersettings',
            name='intro_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('careers/intro/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Tanıtım Görsel'),
        ),
        migrations.AlterField(
            model_name='department',
            name='icon',
            field=models.FileField(blank=True, upload_to=common.utils.UniqueUploadTo('careers/departments/'), validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])], verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cv_file',
            field=models.FileField(upload_to=common.utils.UniqueUploadTo('careers/cv/'), validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='CV Dosyası'),
        ),
    ]
