# Generated by Django 5.1.15 on 2026-06-04 06:32

import common.storage_backends
import common.utils
import common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0014_alter_jobapplication_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv_file',
            field=models.FileField(storage=common.storage_backends.select_cv_storage, upload_to=common.utils.UniqueUploadTo('careers/cv/'), validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx']), common.validators.validate_cv_file], verbose_name='CV Dosyası'),
        ),
    ]
