# Generated by Django 5.1.15 on 2026-03-12 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('kvkk_accepted', models.BooleanField(default=False, verbose_name='KVKK Onayı')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta Başlık')),
                ('meta_title_tr', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık')),
                ('meta_title_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta Açıklama')),
                ('meta_description_tr', models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama')),
                ('meta_description_en', models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama')),
                ('page_title', models.CharField(blank=True, max_length=200, verbose_name='Sayfa Başlığı')),
                ('page_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayfa Başlığı')),
                ('page_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayfa Başlığı')),
                ('hero_image', models.ImageField(blank=True, upload_to='contact/hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Hero Görsel')),
                ('map_embed_url', models.URLField(blank=True, max_length=500, verbose_name='Google Maps Embed URL')),
                ('info_title', models.CharField(blank=True, max_length=200, verbose_name='Bilgi Başlığı')),
                ('info_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bilgi Başlığı')),
                ('info_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bilgi Başlığı')),
                ('info_description', models.TextField(blank=True, verbose_name='Bilgi Açıklaması')),
                ('info_description_tr', models.TextField(blank=True, null=True, verbose_name='Bilgi Açıklaması')),
                ('info_description_en', models.TextField(blank=True, null=True, verbose_name='Bilgi Açıklaması')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('fax', models.CharField(blank=True, max_length=30, verbose_name='Faks')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('address_tr', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('form_title', models.CharField(blank=True, max_length=200, verbose_name='Form Başlığı')),
                ('form_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Form Başlığı')),
                ('form_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Form Başlığı')),
                ('form_subtitle', models.CharField(blank=True, max_length=300, verbose_name='Form Alt Başlığı')),
                ('form_subtitle_tr', models.CharField(blank=True, max_length=300, null=True, verbose_name='Form Alt Başlığı')),
                ('form_subtitle_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Form Alt Başlığı')),
                ('kvkk_text', models.TextField(blank=True, verbose_name='KVKK Onay Metni')),
                ('kvkk_text_tr', models.TextField(blank=True, null=True, verbose_name='KVKK Onay Metni')),
                ('kvkk_text_en', models.TextField(blank=True, null=True, verbose_name='KVKK Onay Metni')),
                ('gallery_images', models.ManyToManyField(blank=True, related_name='contact_pages', to='gallery.galleryimage', verbose_name='Galeri Görselleri')),
            ],
            options={
                'verbose_name': 'İletişim Sayfa Ayarları',
            },
        ),
    ]
