# Generated by Django 5.1.15 on 2026-03-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactpage_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='form_subtitle',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='form_subtitle_en',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='form_subtitle_tr',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='page_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='page_title_en',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='page_title_tr',
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Buton Metni'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA Buton Metni'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_button_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA Buton Metni'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_button_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='CTA Buton URL'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_description',
            field=models.TextField(blank=True, verbose_name='CTA Açıklama'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='CTA Açıklama'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='CTA Açıklama'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Etiket'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA Etiket'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA Etiket'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='CTA Başlık'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CTA Başlık'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='join_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CTA Başlık'),
        ),
    ]
