# Generated by Django 5.1.15 on 2026-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_cleanup_add_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='newsletter_placeholder',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bülten Placeholder'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='newsletter_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bülten Başlığı'),
        ),
    ]
