# Generated by Django 5.1.15 on 2026-04-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_add_newsletter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='newsletter_placeholder_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bülten Placeholder'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='newsletter_placeholder_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bülten Placeholder'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='newsletter_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Başlığı'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='newsletter_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Başlığı'),
        ),
    ]
