# Generated by Django 5.1.15 on 2026-04-01 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactpage_add_newsletter_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='info_image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Kart Görseli'),
        ),
    ]
