# Generated by Django 5.1.15 on 2026-04-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_contact_form_newsletter_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='form_feedback_error_message_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Form Hata Mesajı'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_feedback_error_message_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Form Hata Mesajı'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_feedback_success_message_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Form Başarı Mesajı'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_feedback_success_message_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Form Başarı Mesajı'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_field_email_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-posta Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_field_email_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-posta Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_field_first_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_field_first_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_field_last_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_field_last_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_field_message_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mesaj Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_field_message_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mesaj Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_field_phone_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_field_phone_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_field_subject_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Konu Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_field_subject_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Konu Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_placeholder_email_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-posta Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_placeholder_email_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-posta Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_placeholder_first_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_placeholder_first_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_placeholder_last_name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_placeholder_last_name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_placeholder_message_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mesaj Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_placeholder_message_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mesaj Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_placeholder_phone_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_placeholder_phone_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefon Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_placeholder_subject_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Konu Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_placeholder_subject_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Konu Placeholder'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_privacy_link_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gizlilik Linki Metni'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_privacy_link_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gizlilik Linki Metni'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_submit_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Form Gönder Butonu'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_submit_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Form Gönder Butonu'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_submitting_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Form Gönderiliyor Metni'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_submitting_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Form Gönderiliyor Metni'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='newsletter_error_message_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bülten Hata Mesajı'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='newsletter_error_message_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bülten Hata Mesajı'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='newsletter_submit_aria_label_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Gönder Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='newsletter_submit_aria_label_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Gönder Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='newsletter_success_message_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bülten Başarı Mesajı'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='newsletter_success_message_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bülten Başarı Mesajı'),
        ),
    ]
