# Generated by Django 5.1.15 on 2026-05-22 08:26

import common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_contactpage_form_feedback_error_message_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='info_image',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.UniqueUploadTo('contact/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Kart Görseli'),
        ),
    ]
