# Generated by Django 5.1.15 on 2026-08-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_contactpage_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='form_eyebrow',
            field=models.CharField(blank=True, max_length=100, verbose_name='Form Üst Etiket'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_left_description',
            field=models.TextField(blank=True, verbose_name='Form Sol Açıklama'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_left_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Form Sol Başlık'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_right_eyebrow',
            field=models.CharField(blank=True, max_length=100, verbose_name='Form Sağ Üst Etiket'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_right_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Form Sağ Başlık'),
        ),
    ]
