# Generated by Django 5.1.15 on 2026-03-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta Açıklama')),
                ('logo', models.ImageField(blank=True, upload_to='core/', verbose_name='Logo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('footer_title', models.CharField(blank=True, max_length=200, verbose_name='Footer Başlık')),
                ('footer_newsletter_title', models.CharField(blank=True, max_length=200, verbose_name='Bülten Başlık')),
                ('copyright_text', models.CharField(blank=True, max_length=200, verbose_name='Telif Hakkı')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('location', models.CharField(choices=[('header', 'Üst Menü'), ('footer', 'Alt Menü')], default='header', max_length=10, verbose_name='Konum')),
                ('label', models.CharField(max_length=100, verbose_name='Etiket')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('is_external', models.BooleanField(default=False, verbose_name='Dış Bağlantı')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='core.sitesettings', verbose_name='Site Ayarları')),
            ],
            options={
                'verbose_name': 'Navigasyon Öğesi',
                'verbose_name_plural': 'Navigasyon Öğeleri',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
