# Generated by Django 5.1.15 on 2026-04-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_copy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_tr',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_tr',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_back_to_top_aria_label_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Yukarı Çık Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_back_to_top_aria_label_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Yukarı Çık Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_contact_label_email_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer İletişim E-posta Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_contact_label_email_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer İletişim E-posta Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_contact_label_phone_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer İletişim Telefon Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_contact_label_phone_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer İletişim Telefon Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_contact_label_whatsapp_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer İletişim WhatsApp Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_contact_label_whatsapp_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer İletişim WhatsApp Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_home_aria_label_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Footer Ana Sayfa Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_home_aria_label_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Footer Ana Sayfa Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_newsletter_error_message_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bülten Hata Mesajı'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_newsletter_error_message_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bülten Hata Mesajı'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_newsletter_submit_aria_label_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Gönder Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_newsletter_submit_aria_label_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Gönder Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_newsletter_success_message_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bülten Başarı Mesajı'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_newsletter_success_message_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bülten Başarı Mesajı'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_label_facebook_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook Sosyal Etiket'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_label_facebook_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook Sosyal Etiket'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_label_instagram_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram Sosyal Etiket'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_label_instagram_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram Sosyal Etiket'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_label_linkedin_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn Sosyal Etiket'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_label_linkedin_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn Sosyal Etiket'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_label_x_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='X Sosyal Etiket'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_label_x_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='X Sosyal Etiket'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_label_youtube_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube Sosyal Etiket'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_social_label_youtube_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube Sosyal Etiket'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_desktop_nav_aria_label_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Header Masaüstü Menü Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_desktop_nav_aria_label_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Header Masaüstü Menü Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_home_aria_label_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Header Ana Sayfa Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_home_aria_label_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Header Ana Sayfa Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_locale_button_aria_label_prefix_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Header Dil Butonu Aria Ön Ek'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_locale_button_aria_label_prefix_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Header Dil Butonu Aria Ön Ek'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_mobile_menu_aria_label_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Header Mobil Menü Aç/Kapat Aria'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_mobile_menu_aria_label_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Header Mobil Menü Aç/Kapat Aria'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_mobile_nav_aria_label_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Header Mobil Menü Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_mobile_nav_aria_label_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Header Mobil Menü Aria Etiketi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='not_found_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='404 Açıklama'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='not_found_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='404 Açıklama'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='not_found_primary_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='404 Birincil Buton Metni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='not_found_primary_button_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='404 Birincil Buton Metni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='not_found_secondary_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='404 İkincil Buton Metni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='not_found_secondary_button_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='404 İkincil Buton Metni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='not_found_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='404 Başlık'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='not_found_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='404 Başlık'),
        ),
    ]
