# Generated by Django 5.1.15 on 2026-04-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_meta_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationitem',
            name='label_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Etiket'),
        ),
        migrations.AddField(
            model_name='navigationitem',
            name='label_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Etiket'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telif Hakkı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telif Hakkı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_address_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer Adres Etiketi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_address_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer Adres Etiketi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer İletişim Başlığı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_title_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer İletişim Başlığı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_navigation_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer Navigasyon Başlığı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_navigation_title_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer Navigasyon Başlığı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_consent_link_text_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Rıza Link Metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_consent_link_text_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Rıza Link Metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_consent_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Bülten Rıza Metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_consent_text_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Bülten Rıza Metni'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_placeholder_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Placeholder'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_placeholder_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Placeholder'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Başlık'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_newsletter_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bülten Başlık'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_social_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer Sosyal Başlığı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_social_title_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer Sosyal Başlığı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Footer Başlık'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Footer Başlık'),
        ),
    ]
