# Generated by Django 5.1.15 on 2026-04-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_site_settings_nav_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='fax',
            field=models.CharField(blank=True, max_length=30, verbose_name='Faks'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_label_fax',
            field=models.CharField(blank=True, max_length=100, verbose_name='Footer İletişim Faks Etiketi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_label_fax_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer İletişim Faks Etiketi'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_contact_label_fax_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Footer İletişim Faks Etiketi'),
        ),
    ]
