# Generated by Django 5.1.15 on 2026-05-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seed_legal_footer_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='font_family',
            field=models.CharField(choices=[('dm_sans', 'DM Sans'), ('inter', 'Inter'), ('manrope', 'Manrope'), ('red_hat_display', 'Red Hat Display')], default='dm_sans', max_length=50, verbose_name='Font'),
        ),
    ]
