# Generated by Django 5.1.15 on 2026-05-22 08:26

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_font_family_to_site_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('core/'), verbose_name='Logo'),
        ),
    ]
