# Generated by Django 5.1.15 on 2026-08-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='font_family',
            field=models.CharField(choices=[('dm_sans', 'DM Sans'), ('krub', 'Krub'), ('inter', 'Inter'), ('manrope', 'Manrope'), ('red_hat_display', 'Red Hat Display')], default='dm_sans', max_length=50, verbose_name='Font'),
        ),
    ]
