# Generated by Django 5.1.15 on 2026-09-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_sitesettings_font_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContactSettings',
            fields=[
            ],
            options={
                'verbose_name': 'İletişim ve Haritalar',
                'verbose_name_plural': 'İletişim ve Haritalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sitesettings',),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='apple_maps_url',
            field=models.URLField(blank=True, verbose_name='Apple Maps URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_description',
            field=models.TextField(blank=True, verbose_name='İletişim Bölümü Açıklama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='İletişim Bölümü Açıklama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='İletişim Bölümü Açıklama'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_eyebrow',
            field=models.CharField(blank=True, max_length=100, verbose_name='İletişim Bölümü Eyebrow'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_eyebrow_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İletişim Bölümü Eyebrow'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_eyebrow_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İletişim Bölümü Eyebrow'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='İletişim Bölümü Başlık'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İletişim Bölümü Başlık'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_section_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İletişim Bölümü Başlık'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_url',
            field=models.URLField(blank=True, verbose_name='Google Maps URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='yandex_maps_url',
            field=models.URLField(blank=True, verbose_name='Yandex Maps URL'),
        ),
    ]
