# Generated by Django 5.1.15 on 2026-03-11 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('year', models.CharField(max_length=10, verbose_name='Yıl')),
                ('description', models.TextField(verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Tarihçe Öğesi',
                'verbose_name_plural': 'Tarihçe',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CorporatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta Açıklama')),
                ('hero_image', models.ImageField(blank=True, upload_to='corporate/hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Hero Görsel')),
                ('hero_text', models.CharField(blank=True, max_length=300, verbose_name='Hero Metin')),
                ('about_label', models.CharField(blank=True, max_length=100, verbose_name='Hakkımızda Etiket')),
                ('about_description', models.TextField(blank=True, verbose_name='Hakkımızda Açıklama')),
                ('about_image', models.ImageField(blank=True, upload_to='corporate/about/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Hakkımızda Görsel')),
                ('history_label', models.CharField(blank=True, max_length=100, verbose_name='Hikayemiz Etiket')),
                ('history_title', models.CharField(blank=True, max_length=200, verbose_name='Hikayemiz Başlık')),
                ('vision_icon', models.CharField(blank=True, max_length=100, verbose_name='Vizyon İkon')),
                ('vision_title', models.CharField(blank=True, max_length=200, verbose_name='Vizyon Başlık')),
                ('vision_description', models.TextField(blank=True, verbose_name='Vizyon Açıklama')),
                ('mission_icon', models.CharField(blank=True, max_length=100, verbose_name='Misyon İkon')),
                ('mission_title', models.CharField(blank=True, max_length=200, verbose_name='Misyon Başlık')),
                ('mission_description', models.TextField(blank=True, verbose_name='Misyon Açıklama')),
                ('brands_title', models.CharField(blank=True, max_length=200, verbose_name='Markalar Başlık')),
                ('join_label', models.CharField(blank=True, max_length=100, verbose_name='Katılın Etiket')),
                ('join_title', models.CharField(blank=True, max_length=200, verbose_name='Katılın Başlık')),
                ('join_description', models.TextField(blank=True, verbose_name='Katılın Açıklama')),
                ('join_button_text', models.CharField(blank=True, max_length=100, verbose_name='Buton Metin')),
                ('join_button_url', models.CharField(blank=True, max_length=200, verbose_name='Buton URL')),
            ],
            options={
                'verbose_name': 'Kurumsal Sayfa',
            },
        ),
    ]
