# Generated by Django 5.1.15 on 2026-03-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatehistoryitem',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='corporatehistoryitem',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='about_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Hakkımızda Açıklama'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='about_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Hakkımızda Açıklama'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='about_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hakkımızda Etiket'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='about_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hakkımızda Etiket'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='brands_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Markalar Başlık'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='brands_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Markalar Başlık'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='hero_text_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Hero Metin'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='hero_text_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Hero Metin'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='history_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hikayemiz Etiket'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='history_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hikayemiz Etiket'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='history_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hikayemiz Başlık'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='history_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hikayemiz Başlık'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='join_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Buton Metin'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='join_button_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Buton Metin'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='join_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Katılın Açıklama'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='join_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Katılın Açıklama'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='join_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Katılın Etiket'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='join_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Katılın Etiket'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='join_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Katılın Başlık'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='join_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Katılın Başlık'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='meta_description_tr',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='meta_title_tr',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='mission_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Misyon Açıklama'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='mission_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Misyon Açıklama'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='mission_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Misyon Başlık'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='mission_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Misyon Başlık'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='vision_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Vizyon Açıklama'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='vision_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Vizyon Açıklama'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='vision_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vizyon Başlık'),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='vision_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vizyon Başlık'),
        ),
    ]
