# Generated by Django 5.1.15 on 2026-03-13 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_corporatehistoryitem_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatepage',
            name='about_image',
            field=models.ImageField(blank=True, upload_to='corporate/about/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hakkımızda Görsel'),
        ),
        migrations.AlterField(
            model_name='corporatepage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='corporate/hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görsel'),
        ),
    ]
