# Generated by Django 5.1.15 on 2026-03-13 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_alter_corporatepage_about_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporatepage',
            name='mission_icon',
        ),
        migrations.RemoveField(
            model_name='corporatepage',
            name='vision_icon',
        ),
    ]
