# Generated by Django 5.1.15 on 2026-05-22 08:26

import common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0004_remove_vision_mission_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporatepage',
            name='about_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('corporate/about/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hakkımızda Görsel'),
        ),
        migrations.AlterField(
            model_name='corporatepage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('corporate/hero/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görsel'),
        ),
    ]
