# Generated by Django 5.1.15 on 2026-09-02 10:53

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0005_alter_corporatepage_about_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ALK Group Deneyimi Öğesi',
                'verbose_name_plural': 'ALK Group Deneyimi',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WhySuwItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Neden SUW Öğesi',
                'verbose_name_plural': 'Neden SUW',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='corporatehistoryitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='corporatehistoryitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='corporatehistoryitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='corporatehistoryitem',
            name='title_tr',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='experience_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='experience_description_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='experience_eyebrow_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='experience_eyebrow_tr',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='experience_title_en',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='experience_title_tr',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='final_cta_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='final_cta_description_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='final_cta_eyebrow_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='final_cta_eyebrow_tr',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='final_cta_link',
            field=models.CharField(blank=True, default='/projects', max_length=200),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='final_cta_text_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='final_cta_text_tr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='final_cta_title_en',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='final_cta_title_tr',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='group_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='group_description_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='group_eyebrow_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='group_eyebrow_tr',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='group_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('corporate/group/')),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='group_image_mobile',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('corporate/group/mobile/')),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='group_supporting_label_en',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='group_supporting_label_tr',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='group_title_en',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='group_title_tr',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='hero_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='hero_description_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='hero_eyebrow_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='hero_eyebrow_tr',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='hero_title_tr',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='timeline_eyebrow_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='timeline_eyebrow_tr',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='timeline_title_en',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='timeline_title_tr',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='why_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='why_description_tr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='why_eyebrow_en',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='why_eyebrow_tr',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='why_title_en',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='corporatepage',
            name='why_title_tr',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
