# Generated by Django 5.1.15 on 2026-03-10 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('key', models.CharField(max_length=100, verbose_name='Başlık')),
                ('value', models.CharField(max_length=200, verbose_name='Değer')),
            ],
            options={
                'verbose_name': 'Özellik',
                'verbose_name_plural': 'Özellikler',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeAboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('image', models.ImageField(upload_to='home/about/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Görsel')),
            ],
            options={
                'verbose_name': 'Hakkımızda Görsel',
                'verbose_name_plural': 'Hakkımızda Görseller',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='home/activities/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Görsel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Faaliyet',
                'verbose_name_plural': 'Faaliyetler',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=200, verbose_name='Marka Adı')),
                ('image', models.ImageField(upload_to='home/brands/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('summary', models.TextField(blank=True, verbose_name='Özet')),
                ('image', models.ImageField(upload_to='home/news/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Görsel')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeOperationalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='İkon')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Operasyonel Öğe',
                'verbose_name_plural': 'Operasyonel Öğeler',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta Açıklama')),
                ('brands_title', models.CharField(blank=True, max_length=200, verbose_name='Markalar Başlık')),
                ('brands_description', models.TextField(blank=True, verbose_name='Markalar Açıklama')),
                ('activities_title', models.CharField(blank=True, max_length=200, verbose_name='Faaliyetler Başlık')),
                ('activities_description', models.TextField(blank=True, verbose_name='Faaliyetler Açıklama')),
                ('about_label', models.CharField(blank=True, max_length=100, verbose_name='Hakkımızda Etiket')),
                ('about_title', models.CharField(blank=True, max_length=200, verbose_name='Hakkımızda Başlık')),
                ('about_subtitle', models.CharField(blank=True, max_length=200, verbose_name='Hakkımızda Alt Başlık')),
                ('about_short_description', models.TextField(blank=True, verbose_name='Kısa Açıklama')),
                ('about_long_description', models.TextField(blank=True, verbose_name='Uzun Açıklama')),
                ('operational_label', models.CharField(blank=True, max_length=100, verbose_name='Operasyonel Etiket')),
                ('operational_title', models.CharField(blank=True, max_length=200, verbose_name='Operasyonel Başlık')),
                ('operational_description', models.TextField(blank=True, verbose_name='Operasyonel Açıklama')),
                ('news_section_title', models.CharField(blank=True, max_length=200, verbose_name='Haberler Bölüm Başlık')),
            ],
            options={
                'verbose_name': 'Ana Sayfa',
            },
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Alt Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='home/slides/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Görsel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slider',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeTickerWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('text', models.CharField(max_length=100, verbose_name='Metin')),
            ],
            options={
                'verbose_name': 'Ticker Kelime',
                'verbose_name_plural': 'Ticker Kelimeler',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
