# Generated by Django 5.1.15 on 2026-03-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='video_description',
            field=models.TextField(blank=True, verbose_name='Video Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Video Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video URL'),
        ),
    ]
