# Generated by Django 5.1.15 on 2026-03-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_video_description_homepage_video_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Sayfa Ayarları'},
        ),
        migrations.AddField(
            model_name='homeaboutfeature',
            name='key_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='homeaboutfeature',
            name='key_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='homeaboutfeature',
            name='value_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Değer'),
        ),
        migrations.AddField(
            model_name='homeaboutfeature',
            name='value_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Değer'),
        ),
        migrations.AddField(
            model_name='homeactivity',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='homeactivity',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='homeactivity',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='homeactivity',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='homenews',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='homenews',
            name='summary_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Özet'),
        ),
        migrations.AddField(
            model_name='homenews',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='homenews',
            name='title_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='homeoperationalitem',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='homeoperationalitem',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='homeoperationalitem',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='homeoperationalitem',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hakkımızda Etiket'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hakkımızda Etiket'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_long_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Uzun Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_long_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Uzun Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_short_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Kısa Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hakkımızda Alt Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_subtitle_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hakkımızda Alt Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hakkımızda Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Hakkımızda Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='activities_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Faaliyetler Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='activities_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Faaliyetler Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='activities_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Faaliyetler Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='activities_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Faaliyetler Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='brands_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Markalar Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='brands_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Markalar Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='brands_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Markalar Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='brands_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Markalar Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description_tr',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_title_tr',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_section_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Haberler Bölüm Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_section_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Haberler Bölüm Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='operational_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Operasyonel Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='operational_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Operasyonel Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='operational_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operasyonel Etiket'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='operational_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Operasyonel Etiket'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='operational_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Operasyonel Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='operational_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Operasyonel Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Video Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Video Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Video Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Video Başlık'),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Başlık'),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Başlık'),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='homeslide',
            name='title_tr',
            field=models.CharField(max_length=200, null=True, verbose_name='Başlık'),
        ),
        migrations.AddField(
            model_name='hometickerword',
            name='text_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Metin'),
        ),
        migrations.AddField(
            model_name='hometickerword',
            name='text_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='Metin'),
        ),
    ]
