# Generated by Django 5.1.15 on 2026-03-13 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_homeaboutfeature_key_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeaboutimage',
            name='image',
            field=models.ImageField(upload_to='home/about/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='homeactivity',
            name='image',
            field=models.ImageField(upload_to='home/activities/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='homebrand',
            name='image',
            field=models.ImageField(upload_to='home/brands/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='homenews',
            name='image',
            field=models.ImageField(upload_to='home/news/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='image',
            field=models.ImageField(upload_to='home/slides/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Görsel'),
        ),
    ]
