# Generated by Django 5.1.15 on 2026-03-13 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homeaboutimage_image_alter_homeactivity_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeAboutImage',
        ),
        migrations.DeleteModel(
            name='HomeNews',
        ),
        migrations.DeleteModel(
            name='HomeSlide',
        ),
        migrations.RemoveField(
            model_name='homeactivity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homeactivity',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='homeactivity',
            name='description_tr',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_background_image',
            field=models.ImageField(blank=True, upload_to='home/about/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hakkımızda Arka Plan Görseli'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='home/hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görsel'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Hero Alt Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Hero Alt Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Hero Alt Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Hero Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Hero Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Hero Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_count',
            field=models.PositiveSmallIntegerField(default=6, verbose_name='Anasayfa Haber Sayısı'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='operational_image',
            field=models.ImageField(blank=True, upload_to='home/operational/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Operasyonel Görsel'),
        ),
    ]
