# Generated by Django 5.1.15 on 2026-04-01 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_home_cleanup_add_hero_remove_slide_aboutimage_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='activities_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='Faaliyetler Etiket'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='activities_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Faaliyetler Etiket'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='activities_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Faaliyetler Etiket'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=models.TextField(blank=True, verbose_name='Hero Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Hero Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Hero Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_image',
            field=models.ImageField(blank=True, upload_to='home/video/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Video Arka Plan Görseli'),
        ),
    ]
