# Generated by Django 5.1.15 on 2026-04-10 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepage_add_activities_label_video_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='video_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='video_file',
            field=models.FileField(blank=True, upload_to='home/video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])], verbose_name='Video Dosyası (MP4)'),
        ),
    ]
