# Generated by Django 5.1.15 on 2026-04-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_news_section_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='news_section_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Haberler Buton Metni'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='news_section_button_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Haberler Buton Metni'),
        ),
    ]
