# Generated by Django 5.1.15 on 2026-04-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_seed_homepage_alk_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_cta_button_text',
            field=models.CharField(blank=True, help_text='Buton her zaman Kurumsal sayfasına (/corporate) gider; yalnızca metin düzenlenir.', max_length=100, verbose_name='İstatistikler — buton metni'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_cta_button_text_en',
            field=models.CharField(blank=True, help_text='Buton her zaman Kurumsal sayfasına (/corporate) gider; yalnızca metin düzenlenir.', max_length=100, null=True, verbose_name='İstatistikler — buton metni'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_cta_button_text_tr',
            field=models.CharField(blank=True, help_text='Buton her zaman Kurumsal sayfasına (/corporate) gider; yalnızca metin düzenlenir.', max_length=100, null=True, verbose_name='İstatistikler — buton metni'),
        ),
    ]
