# Generated by Django 5.1.15 on 2026-05-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_seed_about_cta_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeoperationalitem',
            name='external_link_enabled',
            field=models.BooleanField(default=False, verbose_name='Dış Yönlendirme Aktif'),
        ),
        migrations.AddField(
            model_name='homeoperationalitem',
            name='external_url',
            field=models.URLField(blank=True, verbose_name='Dış Yönlendirme URL'),
        ),
    ]
