# Generated by Django 5.1.15 on 2026-05-22 08:26

import common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homeoperationalitem_external_link_help_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeactivity',
            name='image',
            field=models.ImageField(upload_to=common.utils.UniqueUploadTo('home/activities/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='homebrand',
            name='image',
            field=models.ImageField(upload_to=common.utils.UniqueUploadTo('home/brands/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_background_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('home/about/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hakkımızda Arka Plan Görseli'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('home/hero/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görsel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='operational_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('home/operational/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Operasyonel Görsel'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video_file',
            field=models.FileField(blank=True, upload_to=common.utils.UniqueUploadTo('home/video/'), validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])], verbose_name='Video Dosyası (MP4)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='video_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('home/video/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Video Arka Plan Görseli'),
        ),
    ]
