# Generated by Django 5.1.15 on 2026-09-01 14:25

import common.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_production_insights'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTechnicalPerformanceSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Teknik Performans',
                'verbose_name_plural': 'Teknik Performans',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.homepage',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_cta_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Teknik Performans CTA Linki'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_cta_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teknik Performans CTA Metni'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_cta_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teknik Performans CTA Metni'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_cta_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teknik Performans CTA Metni'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_description',
            field=models.TextField(blank=True, verbose_name='Teknik Performans Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Teknik Performans Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Teknik Performans Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_eyebrow',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teknik Performans Eyebrow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_eyebrow_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teknik Performans Eyebrow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_eyebrow_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teknik Performans Eyebrow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('home/technical-performance/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Teknik Performans Görseli'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Teknik Performans Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Teknik Performans Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='technical_performance_title_tr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Teknik Performans Başlık'),
        ),
        migrations.CreateModel(
            name='TechnicalPerformanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(blank=True, max_length=160, verbose_name='Başlık TR')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='Başlık EN')),
                ('description_tr', models.TextField(blank=True, verbose_name='Açıklama TR')),
                ('description_en', models.TextField(blank=True, verbose_name='Açıklama EN')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_performance_items', to='home.homepage', verbose_name='Ana Sayfa')),
            ],
            options={
                'verbose_name': 'Teknik Özellik',
                'verbose_name_plural': 'Teknik Özellikler',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
