# Generated by Django 5.1.15 on 2026-09-01 14:42

import common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_hometechnicalperformancesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCorporateWorkwearSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Kurumsal İş Giyimi',
                'verbose_name_plural': 'Kurumsal İş Giyimi',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.homepage',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_cta_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Kurumsal İş Giyimi CTA Linki'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_cta_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kurumsal İş Giyimi CTA Metni'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_cta_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurumsal İş Giyimi CTA Metni'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_cta_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurumsal İş Giyimi CTA Metni'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_description',
            field=models.TextField(blank=True, verbose_name='Kurumsal İş Giyimi Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Kurumsal İş Giyimi Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Kurumsal İş Giyimi Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_eyebrow',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kurumsal İş Giyimi Eyebrow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_eyebrow_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurumsal İş Giyimi Eyebrow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_eyebrow_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurumsal İş Giyimi Eyebrow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_personnel_description',
            field=models.TextField(blank=True, verbose_name='Personel Kıyafetleri Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_personnel_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Personel Kıyafetleri Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_personnel_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Personel Kıyafetleri Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_personnel_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('home/corporate-workwear/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Personel Kıyafetleri Görseli'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_personnel_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Personel Kıyafetleri Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_personnel_title_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Personel Kıyafetleri Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_personnel_title_tr',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Personel Kıyafetleri Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_promo_description',
            field=models.TextField(blank=True, verbose_name='Promosyon Tekstil Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_promo_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Promosyon Tekstil Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_promo_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Promosyon Tekstil Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_promo_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('home/corporate-workwear/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Promosyon Tekstil Görseli'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_promo_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Promosyon Tekstil Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_promo_title_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Promosyon Tekstil Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_promo_title_tr',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Promosyon Tekstil Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Kurumsal İş Giyimi Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Kurumsal İş Giyimi Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='corporate_workwear_title_tr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Kurumsal İş Giyimi Başlık'),
        ),
    ]
