# Generated by Django 5.1.15 on 2026-09-02 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_homecorporateworkwearsettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProcessSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Fikirden Teslimata',
                'verbose_name_plural': 'Fikirden Teslimata',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.homepage',),
        ),
        migrations.AddField(
            model_name='homepage',
            name='process_description',
            field=models.TextField(blank=True, verbose_name='Süreç Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='process_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Süreç Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='process_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Süreç Açıklama'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='process_eyebrow',
            field=models.CharField(blank=True, max_length=100, verbose_name='Süreç Eyebrow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='process_eyebrow_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Süreç Eyebrow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='process_eyebrow_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Süreç Eyebrow'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='process_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Süreç Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='process_title_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Süreç Başlık'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='process_title_tr',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Süreç Başlık'),
        ),
        migrations.CreateModel(
            name='HomeProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(blank=True, max_length=160, verbose_name='Başlık TR')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='Başlık EN')),
                ('description_tr', models.TextField(blank=True, verbose_name='Açıklama TR')),
                ('description_en', models.TextField(blank=True, verbose_name='Açıklama EN')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='home.homepage', verbose_name='Ana Sayfa')),
            ],
            options={
                'verbose_name': 'Süreç Adımı',
                'verbose_name_plural': 'Süreç Adımları',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
