# Generated by Django 5.1.15 on 2026-03-12 16:53

import common.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('name_tr', models.CharField(max_length=100, null=True, verbose_name='Kategori Adı')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Galeri Kategorisi',
                'verbose_name_plural': 'Galeri Kategorileri',
                'ordering': ('order',),
                'abstract': False,
            },
            bases=(common.models.AutoSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta Başlık')),
                ('meta_title_tr', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık')),
                ('meta_title_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta Açıklama')),
                ('meta_description_tr', models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama')),
                ('meta_description_en', models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Hero Başlık')),
                ('hero_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hero Başlık')),
                ('hero_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hero Başlık')),
                ('hero_image', models.ImageField(blank=True, upload_to='gallery/hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Hero Görsel')),
            ],
            options={
                'verbose_name': 'Galeri Sayfa Ayarları',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='gallery/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Görsel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='gallery.gallerycategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Galeri Görseli',
                'verbose_name_plural': 'Galeri Görselleri',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
