# Generated by Django 5.1.15 on 2026-03-13 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='gallery/hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görsel'),
        ),
    ]
