# Generated by Django 5.1.15 on 2026-03-13 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_galleryimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='intro_text',
            field=models.TextField(blank=True, verbose_name='Giriş Metni'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='intro_text_en',
            field=models.TextField(blank=True, null=True, verbose_name='Giriş Metni'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='intro_text_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Giriş Metni'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Buton Metni'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA Buton Metni'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_button_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA Buton Metni'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_button_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='CTA Buton URL'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_description',
            field=models.TextField(blank=True, verbose_name='CTA Açıklama'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='CTA Açıklama'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='CTA Açıklama'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Etiket'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA Etiket'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA Etiket'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='CTA Başlık'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CTA Başlık'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='join_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CTA Başlık'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='video_description',
            field=models.TextField(blank=True, verbose_name='Video Açıklama'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='video_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Video Açıklama'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='video_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Video Açıklama'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='video_image',
            field=models.ImageField(blank=True, upload_to='gallery/video/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Video Arka Plan Görseli'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='video_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Video Başlık'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='video_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Video Başlık'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='video_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Video Başlık'),
        ),
        migrations.AddField(
            model_name='gallerypage',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Video URL'),
        ),
    ]
