# Generated by Django 5.1.15 on 2026-04-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_gallerypage_showcase_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypage',
            name='lightbox_close_aria_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lightbox Kapat Aria'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='lightbox_close_aria_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lightbox Kapat Aria'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='lightbox_next_aria_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lightbox Sonraki Aria'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='lightbox_next_aria_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lightbox Sonraki Aria'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='lightbox_previous_aria_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lightbox Önceki Aria'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='lightbox_previous_aria_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lightbox Önceki Aria'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='show_more_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Daha Fazla Göster Metni'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='show_more_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Daha Fazla Göster Metni'),
        ),
    ]
