# Generated by Django 5.1.15 on 2026-04-10 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_gallerypage_lightbox_close_aria_label_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='video_file',
            field=models.FileField(blank=True, upload_to='gallery/video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])], verbose_name='Video Dosyası (MP4/WebM)'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Video URL (harici MP4)'),
        ),
    ]
