# Generated by Django 5.1.15 on 2026-05-22 08:26

import common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_gallerypage_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to=common.utils.UniqueUploadTo('gallery/images/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('gallery/hero/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görsel'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='video_file',
            field=models.FileField(blank=True, upload_to=common.utils.UniqueUploadTo('gallery/video/'), validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])], verbose_name='Video Dosyası (MP4/WebM)'),
        ),
        migrations.AlterField(
            model_name='gallerypage',
            name='video_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('gallery/video/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Video Arka Plan Görseli'),
        ),
    ]
