# Generated by Django 5.1.15 on 2026-03-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='news_pages', to='gallery.galleryimage', verbose_name='Galeri Görselleri'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='gallery_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Galeri Başlığı'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='gallery_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Galeri Başlığı'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='gallery_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Galeri Başlığı'),
        ),
    ]
