# Generated by Django 5.1.15 on 2026-03-13 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspage_gallery_images_newspage_gallery_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to='news/hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görsel'),
        ),
    ]
