# Generated by Django 5.1.15 on 2026-04-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_image_alter_newspage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='join_button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Buton Metni'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='join_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA Buton Metni'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='join_button_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA Buton Metni'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='join_button_url',
            field=models.CharField(blank=True, max_length=300, verbose_name='CTA Buton URL'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='join_description',
            field=models.TextField(blank=True, verbose_name='CTA Açıklama'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='join_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='CTA Açıklama'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='join_description_tr',
            field=models.TextField(blank=True, null=True, verbose_name='CTA Açıklama'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='join_label',
            field=models.CharField(blank=True, max_length=100, verbose_name='CTA Etiket'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='join_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA Etiket'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='join_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CTA Etiket'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='join_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='CTA Başlık'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='join_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CTA Başlık'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='join_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CTA Başlık'),
        ),
    ]
