# Generated by Django 5.1.15 on 2026-04-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newspage_copy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='featured_button_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Öne Çıkan Buton Metni'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='featured_button_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Öne Çıkan Buton Metni'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='list_load_more_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Daha Fazla Yükle Metni'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='list_load_more_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Daha Fazla Yükle Metni'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='next_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sonraki Etiketi'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='next_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sonraki Etiketi'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='previous_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Önceki Etiketi'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='previous_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Önceki Etiketi'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='related_title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İlgili Haberler Başlığı'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='related_title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='İlgili Haberler Başlığı'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='related_view_all_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlgili Tümünü Gör Metni'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='related_view_all_text_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='İlgili Tümünü Gör Metni'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='share_title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paylaş Başlığı'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='share_title_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Paylaş Başlığı'),
        ),
    ]
