# Generated by Django 5.1.15 on 2026-05-22 08:26

import common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_seed_news_alk_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=common.utils.UniqueUploadTo('news/images/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('news/hero/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görsel'),
        ),
    ]
