# Generated by Django 5.1.15 on 2026-05-07 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_rename_alkan_detail_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaniesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta Başlık')),
                ('meta_title_tr', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık')),
                ('meta_title_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta Açıklama')),
                ('meta_description_tr', models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama')),
                ('meta_description_en', models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama')),
                ('companies_title', models.CharField(blank=True, max_length=200, verbose_name='Sayfa Başlığı / Hero Başlık')),
                ('companies_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayfa Başlığı / Hero Başlık')),
                ('companies_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayfa Başlığı / Hero Başlık')),
                ('video_file', models.FileField(blank=True, upload_to='companies/video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])], verbose_name='Video Dosyası (MP4)')),
                ('video_image', models.ImageField(blank=True, upload_to='companies/video/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Video Arka Plan Görseli')),
                ('intro_label', models.CharField(blank=True, max_length=100, verbose_name='Giriş Etiket')),
                ('intro_label_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giriş Etiket')),
                ('intro_label_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Giriş Etiket')),
                ('intro_text', models.TextField(blank=True, verbose_name='Giriş Metni')),
                ('intro_text_tr', models.TextField(blank=True, null=True, verbose_name='Giriş Metni')),
                ('intro_text_en', models.TextField(blank=True, null=True, verbose_name='Giriş Metni')),
                ('ticker_description', models.TextField(blank=True, verbose_name='Ticker Alt Açıklama')),
                ('ticker_description_tr', models.TextField(blank=True, null=True, verbose_name='Ticker Alt Açıklama')),
                ('ticker_description_en', models.TextField(blank=True, null=True, verbose_name='Ticker Alt Açıklama')),
                ('milestones_title', models.CharField(blank=True, max_length=200, verbose_name='Tarihçe Başlık')),
                ('milestones_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tarihçe Başlık')),
                ('milestones_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tarihçe Başlık')),
                ('milestones_button_text', models.CharField(blank=True, max_length=100, verbose_name='Tarihçe Buton Metni')),
                ('milestones_button_text_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tarihçe Buton Metni')),
                ('milestones_button_text_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tarihçe Buton Metni')),
                ('milestones_button_url', models.CharField(blank=True, max_length=200, verbose_name='Tarihçe Buton Linki')),
                ('milestones_button_url_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tarihçe Buton Linki')),
                ('milestones_button_url_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tarihçe Buton Linki')),
                ('milestones_year_suffix', models.CharField(blank=True, max_length=50, verbose_name='Yıl Suffix')),
                ('milestones_year_suffix_tr', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yıl Suffix')),
                ('milestones_year_suffix_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Yıl Suffix')),
                ('global_title', models.CharField(blank=True, max_length=200, verbose_name='Global Başlık')),
                ('global_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Global Başlık')),
                ('global_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Global Başlık')),
                ('global_description', models.TextField(blank=True, verbose_name='Global Açıklama')),
                ('global_description_tr', models.TextField(blank=True, null=True, verbose_name='Global Açıklama')),
                ('global_description_en', models.TextField(blank=True, null=True, verbose_name='Global Açıklama')),
                ('global_map_image', models.ImageField(blank=True, upload_to='companies/global/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Harita Görseli')),
                ('countries_text', models.TextField(blank=True, verbose_name='Ülkeler Metni')),
                ('countries_text_tr', models.TextField(blank=True, null=True, verbose_name='Ülkeler Metni')),
                ('countries_text_en', models.TextField(blank=True, null=True, verbose_name='Ülkeler Metni')),
            ],
            options={
                'verbose_name': 'Şirketler Sayfa Ayarları',
            },
        ),
    ]
