# Generated by Django 5.1.15 on 2026-05-15 13:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_add_companies_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetailPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta Başlık')),
                ('meta_title_tr', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık')),
                ('meta_title_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta Açıklama')),
                ('meta_description_tr', models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama')),
                ('meta_description_en', models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama')),
                ('is_active', models.BooleanField(default=False, verbose_name='Detay Sayfası Aktif')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Hero Başlık')),
                ('hero_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hero Başlık')),
                ('hero_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Hero Başlık')),
                ('hero_image', models.ImageField(blank=True, upload_to='brands/company-detail/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görseli')),
                ('logo', models.ImageField(blank=True, upload_to='brands/company-detail/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Logo')),
                ('secondary_logo', models.ImageField(blank=True, upload_to='brands/company-detail/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='İkincil Logo')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Alt Başlık')),
                ('subtitle_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Başlık')),
                ('subtitle_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama / Giriş Metni')),
                ('description_tr', models.TextField(blank=True, null=True, verbose_name='Açıklama / Giriş Metni')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Açıklama / Giriş Metni')),
                ('cta_label', models.CharField(blank=True, max_length=100, verbose_name='Buton Metni')),
                ('cta_label_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Buton Metni')),
                ('cta_label_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Buton Metni')),
                ('cta_url', models.URLField(blank=True, verbose_name='Buton Linki')),
                ('feature_image_1', models.ImageField(blank=True, upload_to='brands/company-detail/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Öne Çıkan Görsel 1')),
                ('feature_image_2', models.ImageField(blank=True, upload_to='brands/company-detail/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Öne Çıkan Görsel 2')),
                ('bottom_paragraph', models.TextField(blank=True, verbose_name='Alt Paragraf')),
                ('bottom_paragraph_tr', models.TextField(blank=True, null=True, verbose_name='Alt Paragraf')),
                ('bottom_paragraph_en', models.TextField(blank=True, null=True, verbose_name='Alt Paragraf')),
                ('sub_brands_title', models.CharField(blank=True, max_length=200, verbose_name='Alt Marka Başlığı')),
                ('sub_brands_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Marka Başlığı')),
                ('sub_brands_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Alt Marka Başlığı')),
                ('has_global_block', models.BooleanField(default=False, verbose_name='Global Operasyon Bloğu Göster')),
                ('global_block_title', models.CharField(blank=True, max_length=200, verbose_name='Global Blok Başlık')),
                ('global_block_title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Global Blok Başlık')),
                ('global_block_title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Global Blok Başlık')),
                ('global_block_description', models.TextField(blank=True, verbose_name='Global Blok Açıklama')),
                ('global_block_description_tr', models.TextField(blank=True, null=True, verbose_name='Global Blok Açıklama')),
                ('global_block_description_en', models.TextField(blank=True, null=True, verbose_name='Global Blok Açıklama')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='İletişim Kişisi')),
                ('contact_name_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='İletişim Kişisi')),
                ('contact_name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='İletişim Kişisi')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='İletişim E-posta')),
                ('contact_website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_page', to='brands.groupcompany', verbose_name='Şirket')),
                ('sub_brands', models.ManyToManyField(blank=True, related_name='company_detail_pages', to='brands.brand', verbose_name='Alt Markalar')),
            ],
            options={
                'verbose_name': 'Şirket Detay Sayfası',
                'verbose_name_plural': 'Şirket Detay Sayfaları',
            },
        ),
    ]
