# Generated by Django 5.1.15 on 2026-05-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_companydetailpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='show_external_link',
            field=models.BooleanField(default=True, verbose_name='Dış Bağlantıyı Göster'),
        ),
        migrations.AddField(
            model_name='globaloperationlocation',
            name='page_scope',
            field=models.CharField(choices=[('brands', 'Markalar Sayfası'), ('companies', 'Şirketler Sayfası')], default='brands', max_length=16, verbose_name='Kullanıldığı Sayfa'),
        ),
    ]
