# Generated by Django 5.1.15 on 2026-05-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_globaloperationlocation_help_texts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsOperationLocation',
            fields=[
            ],
            options={
                'verbose_name': 'Operasyon Lokasyonu · Markalar',
                'verbose_name_plural': 'Operasyon Lokasyonları · Markalar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('brands.globaloperationlocation',),
        ),
        migrations.CreateModel(
            name='CompaniesOperationLocation',
            fields=[
            ],
            options={
                'verbose_name': 'Operasyon Lokasyonu · Şirketler',
                'verbose_name_plural': 'Operasyon Lokasyonları · Şirketler',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('brands.globaloperationlocation',),
        ),
        migrations.AddField(
            model_name='brandspage',
            name='use_custom_timeline',
            field=models.BooleanField(default=False, help_text="Kapalıysa kurumsal tarihçe öğeleri (Kurumsal → Tarihçe) gösterilir. Açıksa aşağıdaki 'Kronolojik Zaman Çizelgesi' kayıtları kullanılır.", verbose_name='Özel Zaman Çizelgesi Kullan'),
        ),
    ]
