# Generated by Django 5.1.15 on 2026-05-22 08:26

import common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_use_custom_timeline_and_operation_location_proxies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akalgmbhpage',
            name='feature_image_1',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Öne Çıkan Görsel 1'),
        ),
        migrations.AlterField(
            model_name='akalgmbhpage',
            name='feature_image_2',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Öne Çıkan Görsel 2'),
        ),
        migrations.AlterField(
            model_name='akalgmbhpage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görseli'),
        ),
        migrations.AlterField(
            model_name='akalgmbhpage',
            name='logo',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='akalgmbhpage',
            name='secondary_logo',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='İkincil Logo (Nordbron)'),
        ),
        migrations.AlterField(
            model_name='akalpage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görseli'),
        ),
        migrations.AlterField(
            model_name='akalpage',
            name='logo',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='alkanpage',
            name='feature_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Öne Çıkan Görsel'),
        ),
        migrations.AlterField(
            model_name='alkanpage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görseli'),
        ),
        migrations.AlterField(
            model_name='alkanpage',
            name='logo',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='card_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/cards/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Kart Görseli'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(upload_to=common.utils.UniqueUploadTo('brands/logos/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='show_external_link',
            field=models.BooleanField(default=True, verbose_name='Dış Bağlantıyı Göster'),
        ),
        migrations.AlterField(
            model_name='brandspage',
            name='global_map_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/global/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Harita Görseli'),
        ),
        migrations.AlterField(
            model_name='brandspage',
            name='use_custom_timeline',
            field=models.BooleanField(default=False, verbose_name='Özel Zaman Çizelgesi Kullan'),
        ),
        migrations.AlterField(
            model_name='brandspage',
            name='video_file',
            field=models.FileField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/video/'), validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])], verbose_name='Video Dosyası (MP4)'),
        ),
        migrations.AlterField(
            model_name='brandspage',
            name='video_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/video/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Video Arka Plan Görseli'),
        ),
        migrations.AlterField(
            model_name='companiespage',
            name='global_map_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('companies/global/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Harita Görseli'),
        ),
        migrations.AlterField(
            model_name='companiespage',
            name='video_file',
            field=models.FileField(blank=True, upload_to=common.utils.UniqueUploadTo('companies/video/'), validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])], verbose_name='Video Dosyası (MP4)'),
        ),
        migrations.AlterField(
            model_name='companiespage',
            name='video_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('companies/video/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Video Arka Plan Görseli'),
        ),
        migrations.AlterField(
            model_name='companydetailpage',
            name='feature_image_1',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Öne Çıkan Görsel 1'),
        ),
        migrations.AlterField(
            model_name='companydetailpage',
            name='feature_image_2',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Öne Çıkan Görsel 2'),
        ),
        migrations.AlterField(
            model_name='companydetailpage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görseli'),
        ),
        migrations.AlterField(
            model_name='companydetailpage',
            name='logo',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='companydetailpage',
            name='secondary_logo',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='İkincil Logo'),
        ),
        migrations.AlterField(
            model_name='groupcompany',
            name='logo',
            field=models.ImageField(upload_to=common.utils.UniqueUploadTo('brands/companies/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='suwpage',
            name='feature_image_1',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Öne Çıkan Görsel 1'),
        ),
        migrations.AlterField(
            model_name='suwpage',
            name='feature_image_2',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Öne Çıkan Görsel 2'),
        ),
        migrations.AlterField(
            model_name='suwpage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görseli'),
        ),
        migrations.AlterField(
            model_name='suwpage',
            name='logo',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('brands/company-detail/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Logo'),
        ),
    ]
