# Generated by Django 5.1.15 on 2026-04-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalsection',
            options={'ordering': ('order',), 'verbose_name': 'Yasal Sayfa Bölümü', 'verbose_name_plural': 'Yasal Sayfa Bölümleri'},
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='intro_en',
            field=models.TextField(blank=True, null=True, verbose_name='Giriş Metni'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='intro_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Giriş Metni'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='last_updated_label_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Son Güncelleme Etiketi'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='last_updated_label_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Son Güncelleme Etiketi'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='meta_description',
            field=models.TextField(blank=True, max_length=320, verbose_name='Meta Açıklama'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='meta_description_tr',
            field=models.TextField(blank=True, max_length=320, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Başlık'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='meta_title_tr',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Başlık'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='subtitle_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Alt Başlık'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='title_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='legalsection',
            name='body_en',
            field=models.JSONField(default=list, help_text='Her satır ayrı bir paragraf. JSON string array: ["paragraf1", "paragraf2"]', null=True, verbose_name='Bölüm İçeriği'),
        ),
        migrations.AlterField(
            model_name='legalsection',
            name='body_tr',
            field=models.JSONField(default=list, help_text='Her satır ayrı bir paragraf. JSON string array: ["paragraf1", "paragraf2"]', null=True, verbose_name='Bölüm İçeriği'),
        ),
        migrations.AlterField(
            model_name='legalsection',
            name='heading_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bölüm Başlığı'),
        ),
        migrations.AlterField(
            model_name='legalsection',
            name='heading_tr',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Bölüm Başlığı'),
        ),
        migrations.AlterField(
            model_name='legalsection',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
