# Generated by Django 5.1.15 on 2026-05-22 08:26

import common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0003_seed_gizlilik_ve_cerez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalpage',
            name='hero_glow_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('legal/hero/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'svg'])], verbose_name='Hero Glow Görsel'),
        ),
        migrations.AlterField(
            model_name='legalpage',
            name='hero_image',
            field=models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('legal/hero/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Hero Görsel'),
        ),
    ]
