# Generated by Django 5.1.15 on 2026-08-31 06:13

import common.models
import common.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=120, verbose_name='Türkçe ad')),
                ('name_en', models.CharField(max_length=120, verbose_name='İngilizce ad')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('products/groups/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('short_description_tr', models.TextField(blank=True)),
                ('short_description_en', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ürün grubu',
                'verbose_name_plural': 'Ürün grupları',
                'ordering': ['sort_order', 'id'],
            },
            bases=(common.models.AutoSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=120, verbose_name='Türkçe ad')),
                ('name_en', models.CharField(max_length=120, verbose_name='İngilizce ad')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('image', models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('products/categories/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('description_tr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='categories', to='products.productgroup')),
            ],
            options={
                'verbose_name': 'Ürün kategorisi',
                'verbose_name_plural': 'Ürün kategorileri',
                'ordering': ['sort_order', 'id'],
            },
            bases=(common.models.AutoSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tr', models.CharField(max_length=180, verbose_name='Türkçe ad')),
                ('name_en', models.CharField(max_length=180, verbose_name='İngilizce ad')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('product_code', models.CharField(max_length=80, unique=True)),
                ('short_description_tr', models.TextField(blank=True)),
                ('short_description_en', models.TextField(blank=True)),
                ('description_tr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, upload_to=common.utils.UniqueUploadTo('products/items/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory')),
                ('groups', models.ManyToManyField(blank=True, related_name='products', to='products.productgroup')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['sort_order', 'id'],
            },
            bases=(common.models.AutoSlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=common.utils.UniqueUploadTo('products/gallery/'), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('alt_tr', models.CharField(blank=True, max_length=200)),
                ('alt_en', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Ürün görseli',
                'verbose_name_plural': 'Ürün görselleri',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
